### PR TITLE
CLOUD-2338 split jboss-image-stream.json file into individual product…

### PR DESCRIPTION
**Pull request by rcernich**
… files

Signed-off-by: rcernich <rcernich@redhat.com>

### CODE REVIEW

**Comment by kyguy** [comment]
Verified AMQ templates

**Comment by spolti** [comment]
BxMS looks good.
Just one question: Do we need to keep old image streams since the images are not available in the registry? Example process server 63 and decision server 62.

**Comment by rcernich** [comment]
> Just one question: Do we need to keep old image streams since the images are not available in the registry? Example process server 63 and decision server 62.

If customers are still using the old versions, they'll need these if they update their OpenShift instances or do new installs.  The images are still available, they're just deprecated.  That said, we've since nuked the related templates and they could always use an older tag.  Now I'm thinking we don't need the extra standalone definitions of deprecated images.

**Comment by iankko** [comment]
JFTR Verified sso image streams and templates work fine too.

**Pull request merged**
