### PR TITLE
[CLOUD-940] Expose the MAVEN_MIRROR_URL variable for EAP 6/7

### PR DESCRIPTION
**Pull request by osnipso**
If set, it will be used by s2i while building sources.

### CODE REVIEW

**Comment by jwendell** [comment]
The parameters are missing the displayName property.

**Comment by rcernich** [comment]
Good catch, @jwendell.

**Comment by osnipso** [comment]
@jwendell @rcernich done. Did for the others, too.

**Comment by jwendell** [comment]
The displayName field should be the first, above description. Take a look at the others.
(disclaimer: this is not my idea, but we should keep the consistency. See Marko's comment on https://github.com/jboss-openshift/application-templates/pull/226)

This apply to the other PR's as well.

**Comment by osnipso** [comment]
@jwendell done for this one, doing for the others. Thanks.

**Comment by luksa** [comment]
LGTM

**Comment by osnipso** [comment]
Done.

**Comment by osnipso** [comment]
Closing, replaced by [#250](https://github.com/jboss-openshift/application-templates/pull/250)

**Pull request closed without merging**
