### PR TITLE
[CLOUD-987] Add messages to be shown upon instantiation

### PR DESCRIPTION
**Pull request by jwendell**

### CODE REVIEW

**Comment by jwendell** [comment]
This is a WIP for the CLOUD-987 work.
Splitting the work into projects makes it easier to review.

@rcernich Do you prefer me to create a PR for each product or I can just add commits into this one and merge them all together in a single step?

**Comment by rcernich** [comment]
There was only a single issue for this, so if you choose to split it up into individual commits, that's fine.  I'd prefer a single PR as that's less work for me.

**Comment by rcernich** [comment]
These look great!

**Comment by jwendell** [comment]
@rcernich done. You can start the review.

**Pull request merged**
