### PR TITLE
[CLOUD-1852] bpmsuite: add business central volume config

### PR DESCRIPTION
**Pull request by psiroky**
@errantepiphany could you please take a quick look?

### CODE REVIEW

**Comment by psiroky** [comment]
Right. So I guess this will need to stay open until we have that template. Or should I create the template as part of this PR?

**Comment by errantepiphany** [comment]
You can update this PR if you want. Remove your changes from that file, copy it to a "-persistent" one, and add your changes to that. Then "push -f" to update this PR.

**Comment by psiroky** [comment]
OK. I am assuming we want to setup a persistence for the MySQL as well? I can just copy the configs from the other templates, so that should be fine.

**Comment by errantepiphany** [comment]
Yup, MySQL too. Everything in the persistent template should be. Thanks! :)

**Comment by psiroky** [comment]
@errantepiphany this should be ready now.

**Comment by errantepiphany** [comment]
@psiroky Hi Petr. Looks good, except there are a few new parameters that need to be added. You can look at the other json file for example, but please add in MAVEN_REPO_URL, MAVEN_REPO_SERVICE, MAVEN_REPO_PATH, MAVEN_REPO_USERNAME, MAVEN_REPO_PASSWORD. Once those are back in and matching the other template, I will sign off on this one. Thanks again!

**Comment by psiroky** [comment]
@errantepiphany hopefully fixed now

**Comment by errantepiphany** [comment]
Looks good! Merging...

**Pull request merged**
