### PR TITLE
[CLOUD-940] Expose the MAVEN_MIRROR_URL variable for JWS

### PR DESCRIPTION
**Pull request by osnipso**
If set, it will be used by s2i while building sources.

### CODE REVIEW

**Comment by jwendell** [comment]
The parameters are missing the displayName property.

**Comment by osnipso** [comment]
@jwendell done, one more to go.

**Comment by osnipso** [comment]
@jwendell changed the order, displayName now appears first. Doing for the others.

**Comment by luksa** [comment]
LGTM, except maybe change "s2i" in the description to uppercase.

**Comment by osnipso** [comment]
Done.

**Comment by osnipso** [comment]
Closing, replaced by [#251](https://github.com/jboss-openshift/application-templates/pull/251)

**Pull request closed without merging**
