### PR TITLE
provide file with all available imagestreams

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
@rcernich WDYT about this or somethign similar? I can create a jira for it if its something we think would be useful.

I think it would be useful for scripting the import of all of the available images, like say when using MiniShift or oc cluster up.

**Comment by rcernich** [comment]
@luck3y, I agree, but it also assumes everything is released at the same time.  If we have images being released over days/weeks, how do we ensure what gets updated is what's actually been released?  This is probably a weak argument, because if we tagged it, then everything should be in the release pipeline, so barring anything catastrophic, it would be released at some point.  This would be a way to import everything at once though.

Taking it a step further, maybe we create these for each product to handle all of the resources, templates and image stream definitions.

**Comment by luck3y** [comment]
@rcernich Yeah, I mean at the time it was tagged, the contents of the file should match whatever streams are available in the repo.

The con is its one more thing to maintain, and i guess we could compensate with scripting anyway.

The one use case that we'll see over and over is the shell loop in errata for every product to update both the stream and the templates. So it would be nice if this was reducable to something a lot simpler, less error prone and easy to check / test.

This isn't that either, so now I'm thinking this isn't such a good idea anymore, but some scripting possibly would be.

**Comment by rcernich** [comment]
Yeah, which is why I suggested it for each product.  Moving forward, all these updates will probably happen one product at a time.  It's nice to have an index though.  Getting the readme updated would help a lot too.

**Comment by rcernich** [comment]
No hinting.  It's something that I really need to do.

**Comment by luck3y** [comment]
going to close this for now, and think about alternatives.

**Pull request closed without merging**
