### PR TITLE
restore amq62-image-stream.json

### PR DESCRIPTION
**Pull request by gaohoward**
Signed-off-by: Howard Gao <howard.gao@gmail.com>

### CODE REVIEW

**Comment by rcernich** [comment]
Can you also make the updates to move from registry.access.redhat.com to registry.redhat.io, which should also include adding the "local" policy to the image stream definitions (look at any one of the other image streams for an example of what to do)?  TIA

**Comment by gaohoward** [comment]
@rcernich ok will do. Thanks.

**Comment by bparees** [comment]
+1 on @rcernich's comment.

**Comment by bparees** [comment]
lgtm also.

**Comment by rcernich** [comment]
merged.  There should be a new tag the end of next week.

**Pull request merged**
