### PR TITLE
[CLOUD-1852] bpmsuite: fix BC volume mount path

### PR DESCRIPTION
**Pull request by psiroky**
@errantepiphany can you please take a look and merge?

cc @sutaakar

### CODE REVIEW

**Comment by sutaakar** [comment]
Should fix Workbench persistence functionality when merged together with https://github.com/jboss-openshift/cct_module/pull/33

**Comment by psiroky** [comment]
Could we please get this in? cc @goldmann

**Comment by errantepiphany** [comment]
@psiroky Merged.

**Comment by psiroky** [comment]
@errantepiphany thanks!

**Pull request merged**
