### PR TITLE
[CLOUD-940] Expose the MAVEN_MIRROR_URL variable for kieserver

### PR DESCRIPTION
**Pull request by osnipso**
If set, it will be used by s2i while building sources.

### CODE REVIEW

**Comment by jwendell** [comment]
The parameters are missing the displayName property.

**Comment by osnipso** [comment]
@jwendell done. Doing for the other PRs.

**Comment by osnipso** [comment]
@jwendell changed the order on this one too, displayName appearing first. One more to go.

**Comment by osnipso** [comment]
S2I in uppercase - done.

**Comment by rcernich** [comment]
@osnipso, could you please move these to a working branch?  It's generally dangerous to do work on a tracking branch, as it could cause problems the next time you pull (e.g. if your pr was rebased before merging).  For CE, the general practice is to use the issue id for the branch name, e.g. CLOUD-940-kie.

**Comment by osnipso** [comment]
Closing, replaced by [#252](https://github.com/jboss-openshift/application-templates/pull/252)

**Pull request closed without merging**
