### PR TITLE
CLOUD-2965 move openjdk resources to openjdk container repository

### PR DESCRIPTION
**Pull request by rcernich**
Signed-off-by: rcernich <rcernich@redhat.com>

### CODE REVIEW

**Comment by rcernich** [comment]
They are [here](https://github.com/jboss-container-images/openjdk/blob/openjdk18-dev/templates/image-streams.json) but it looks like the default branches have changed.  @goldmann, do we need to merge openjdk18-dev into the develop branch?

**Comment by goldmann** [comment]
@rcernich I created the `develop` branch and made it default a few days ago, because it did not make sense to have a `openjdkXY-dev` branch where we drop all the versions of this image in the same branch. I notified @jmtd, the new image owner, about this change. The `openjdkXY-dev` and `openjdkXY` branches should be dropped and `master`/`develop` scheme should be used from now on.

Regarding templates, it looks like this change went into `openjdk18-dev` branch. I suggest to rebase `develop` branch with this change and re-push. This could be issue on my side where I did not use proper HEAD of the `openjdk18-dev` branch to create develop.

**Comment by rcernich** [comment]
I merged the openjdk18-dev branch into develop.  It looks like two commits were missing.  The two branches should be in sync now.

**Comment by jmtd** [comment]
I've just stumbled across this, after I did sprint 27 builds from the openjdk18-dev branch (for 8 and 11). It looks like the main commit these builds will be missing is 7fedb02bd7ae553ed59a3d180ab5db990e35ea32 which only touches the CTF tests.

**Comment by goldmann** [comment]
@jmtd Please note that the ARQ tests now fail, because these were not updated to point to the new repository.

**Pull request merged**
