### PR TITLE
[CLOUD-2242] Added transaction recovery templates for JDG 6.5 and 7.1, JDV 6.3 and Process Server 6.4

### PR DESCRIPTION
**Pull request by douglaspalmer**
…5 and 7.1, JDV 6.3 and Process Server 6.4

### CODE REVIEW

**Comment by rcernich** [comment]
Hey @douglaspalmer, we decided to move these changes to sprint 14 and will create a new jira for that work.  I took your changes for eap71 and added them in another commit, so you'll have to remove those changes from this commit (sorry).

**Comment by douglaspalmer** [comment]
No problem, I've removed EAP7.1 from this PR.

**Comment by rcernich** [comment]
Thanks @douglaspalmer!  I've created CLOUD-2242 for the this work.  If you could update the commit message, that would be great.  Thanks again!

**Comment by douglaspalmer** [comment]
Done

**Pull request closed without merging**
