### PR TITLE
update imagestreams to registry.redhat.io

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@rcernich these updates are necessary to switch over to the new redhat registry.  A couple notes:

1) there are several imagestream files that do not exist in master, so i do not have a good way to update them...  for those files you're going to need to update them yourself and fix up openshift/library to pick them up.  The references in question are:

https://raw.githubusercontent.com/jboss-openshift/application-templates/{amq_version}/amq/amq62-image-stream.json

https://raw.githubusercontent.com/jboss-openshift/application-templates/{xpaas_version}/jboss-image-streams.json

2) after this PR is merged and you fix up the other content from (1), you'll need to cut a new tag and go update openshift/library to use that new tag so we pick up the changes.

please let me know if you have any questions.

**Comment by rcernich** [comment]
Hey @bparees, what's the timeframe for completing this?  It's on our radar, but I'm not sure of the urgency.

**Comment by bparees** [comment]
@rcernich that's a little hard to assess since the old registry isn't going away, but we're currently carrying a patch in our origin repos for your imagestreams to cover this change.  The sooner we can get them re-aligned the easier my life gets.

A week would be nice.

**Comment by rcernich** [comment]
Added to our next sprint: https://issues.jboss.org/browse/CLOUD-2751

**Comment by iankko** [comment]
Verified, the RH-SSO images work properly with this change. ACK for the RH-SSO images part.

@kyguy @osnipso @spolti @errantepiphany @luck3y @bekionel Could you please check, the change works fine for your images too? The testing procedure I used is described in KEYCLOAK-8165.

**Comment by rcernich** [comment]
manually rebased and merged

**Pull request closed without merging**
