### PR TITLE
CLOUD-664 update persistent templates to support meshing; update image version to 1.3

### PR DESCRIPTION
**Pull request by rcernich**

### CODE REVIEW

**Comment by dsimansk** [comment]
Hi Rob(@rcernich ),
I've noticed there's `$ACTIVEMQ_SPLIT` in your PR, should it be rather `$AMQ_SPLIT` as per CLODU-664 and conversation here https://github.com/jboss-openshift/application-templates/pull/148

**Comment by rcernich** [comment]
Good catch.  Thanks!

**Comment by rcernich** [comment]
fixed split parameter/variable.  added jolokia port to amq deployments in eap+amq templates.  added eap70-amq-persistent-s2i template.

**Comment by rcernich** [comment]
added split/mesh flags to eap+amq persistent templates

**Pull request merged**
