### PR TITLE
fix capitalization of GitHub trigger type

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@knrc @rcernich ptal.

**Comment by bparees** [comment]
this is for https://bugzilla.redhat.com/show_bug.cgi?id=1247461

**Comment by knrc** [comment]
I can't find a JIRA for this, did you create one?

**Comment by bparees** [comment]
I did not.

created one now:
https://issues.jboss.org/browse/CLOUD-191

**Pull request merged**
